### ISSUE TITLE
"Category id" is displayed on browser's title when a category is selected

### ISSUE THREAD

**Issue by betzerra** [Canillitapp/headlines-web#6]
![screenshot 2019-02-06 23 26 45](https://user-images.githubusercontent.com/681600/52386986-260e9a00-2a67-11e9-8485-14ba894ad58f.png)

**Comment by sergiofruto** [comment]
Question: what's the right fix here?
Because this happens in some, but in others you can the label just fine (image attached).
Should we always keep the "Canillitapp" or we should display the name of the category?
![image](https://user-images.githubusercontent.com/4473420/52459727-a3a8d780-2b45-11e9-92d3-56ab0db34d22.png)

**Comment by betzerra** [comment]
@sergiofruto I'm not a fan of hardcoding values **BUT** since we're [_kind of_ doing it here](https://github.com/Canillitapp/headlines-web/blob/master/pages/category.js#L53), let's keep this format `{category} | Canillitapp`.

In order to avoid having multiple sources of truth I would recommend to extract that logic in a js / config file if possible. Something like:

```
categories = [
  { "key" : "Política", "id" : 1 },
  { "key" : "Internacionales", "id" : 2},
  { "key" : "Tecnología", "id" : 3},
  { "key" : "Espectáculos", "id" : 4}
]
```
